package alektas.midic.theme

import androidx.compose.ui.graphics.Color

val light_primary = Color(0xFFedab02)
val light_onPrimary = Color(0xFFffffff)
val light_primaryContainer = Color(0xFFfcf3e5)
val light_onPrimaryContainer = Color(0xFF201c00)
val light_secondary = Color(0xFF655f41)
val light_onSecondary = Color(0xFFffffff)
val light_secondaryContainer = Color(0xFFfff9f1)
val light_onSecondaryContainer = Color(0xFF201c05)
val light_tertiary = Color(0xFF416651)
val light_onTertiary = Color(0xFFffffff)
val light_tertiaryContainer = Color(0xFFc2ecd1)
val light_onTertiaryContainer = Color(0xFF002111)
val light_error = Color(0xFFba1b1b)
val light_errorContainer = Color(0xFFffdad4)
val light_onError = Color(0xFFffffff)
val light_onErrorContainer = Color(0xFF410001)
val light_background = Color(0xFFfffdf9)
val light_onBackground = Color(0xFF1d1c16)
val light_surface = Color(0xFFfff9f1)
val light_onSurface = Color(0xFF1d1c16)
val light_surfaceVariant = Color(0xFFfcf3e5)
val light_onSurfaceVariant = Color(0xFF4a473a)
val light_outline = Color(0xFF7b7768)
val light_inverseOnSurface = Color(0xFFf5f0e7)
val light_inverseSurface = Color(0xFF32302a)

val dark_primary = Color(0xFFdbc84e)
val dark_onPrimary = Color(0xFF383000)
val dark_primaryContainer = Color(0xFF514700)
val dark_onPrimaryContainer = Color(0xFFf8e467)
val dark_secondary = Color(0xFFcfc7a2)
val dark_onSecondary = Color(0xFF353117)
val dark_secondaryContainer = Color(0xFF4c472b)
val dark_onSecondaryContainer = Color(0xFFece3bd)
val dark_tertiary = Color(0xFFa7d0b6)
val dark_onTertiary = Color(0xFF123725)
val dark_tertiaryContainer = Color(0xFF294e3a)
val dark_onTertiaryContainer = Color(0xFFc2ecd1)
val dark_error = Color(0xFFffb4a9)
val dark_errorContainer = Color(0xFF930006)
val dark_onError = Color(0xFF680003)
val dark_onErrorContainer = Color(0xFFffdad4)
val dark_background = Color(0xFF1d1c16)
val dark_onBackground = Color(0xFFe7e2d9)
val dark_surface = Color(0xFF1d1c16)
val dark_onSurface = Color(0xFFe7e2d9)
val dark_surfaceVariant = Color(0xFF4a473a)
val dark_onSurfaceVariant = Color(0xFFccc6b4)
val dark_outline = Color(0xFF969181)
val dark_inverseOnSurface = Color(0xFF1d1c16)
val dark_inverseSurface = Color(0xFFe7e2d9)
