package alektas.midic.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF6b5e00)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFf8e467)
val md_theme_light_onPrimaryContainer = Color(0xFF201c00)
val md_theme_light_secondary = Color(0xFF655f41)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFece3bd)
val md_theme_light_onSecondaryContainer = Color(0xFF201c05)
val md_theme_light_tertiary = Color(0xFF416651)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFc2ecd1)
val md_theme_light_onTertiaryContainer = Color(0xFF002111)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfffbf7)
val md_theme_light_onBackground = Color(0xFF1d1c16)
val md_theme_light_surface = Color(0xFFfffbf7)
val md_theme_light_onSurface = Color(0xFF1d1c16)
val md_theme_light_surfaceVariant = Color(0xFFe8e2d0)
val md_theme_light_onSurfaceVariant = Color(0xFF4a473a)
val md_theme_light_outline = Color(0xFF7b7768)
val md_theme_light_inverseOnSurface = Color(0xFFf5f0e7)
val md_theme_light_inverseSurface = Color(0xFF32302a)

val md_theme_dark_primary = Color(0xFFdbc84e)
val md_theme_dark_onPrimary = Color(0xFF383000)
val md_theme_dark_primaryContainer = Color(0xFF514700)
val md_theme_dark_onPrimaryContainer = Color(0xFFf8e467)
val md_theme_dark_secondary = Color(0xFFcfc7a2)
val md_theme_dark_onSecondary = Color(0xFF353117)
val md_theme_dark_secondaryContainer = Color(0xFF4c472b)
val md_theme_dark_onSecondaryContainer = Color(0xFFece3bd)
val md_theme_dark_tertiary = Color(0xFFa7d0b6)
val md_theme_dark_onTertiary = Color(0xFF123725)
val md_theme_dark_tertiaryContainer = Color(0xFF294e3a)
val md_theme_dark_onTertiaryContainer = Color(0xFFc2ecd1)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1d1c16)
val md_theme_dark_onBackground = Color(0xFFe7e2d9)
val md_theme_dark_surface = Color(0xFF1d1c16)
val md_theme_dark_onSurface = Color(0xFFe7e2d9)
val md_theme_dark_surfaceVariant = Color(0xFF4a473a)
val md_theme_dark_onSurfaceVariant = Color(0xFFccc6b4)
val md_theme_dark_outline = Color(0xFF969181)
val md_theme_dark_inverseOnSurface = Color(0xFF1d1c16)
val md_theme_dark_inverseSurface = Color(0xFFe7e2d9)

val seed = Color(0xFFe5d257)
val error = Color(0xFFba1b1b)